export const jdbslotimg = [
    {
      name: "Fortune Jewel",
      img: "https://i.ibb.co/108h3Lw/Jewel.png",
      gameId: 14095,
      gType: 0,
      category: "Slot",
    },
    {
      name: "Magic Ace WILD LOCK",
      img: "https://i.ibb.co/HBNzXGG/Magic.png",
      gameId: 14093,
      gType: 0,
      category: "Slot",
    },
    {
      name: "Bull Treasure",
      img: "https://i.ibb.co/LQrvfQ5/Bull.png",
      gameId: 14094,
      gType: 0,
      category: "Slot",
    },
    {
      name: "Dragon Soar - Hyper Wild",
      img: "https://i.ibb.co/HrznyS7/Dragon.png",
      gameId: 14092,
      gType: 0,
      category: "Slot",
    },
    {
      name: "Piggy Bank",
      img: "https://i.ibb.co/sCm3wHJ/Piggy.png",
      gameId: 14091,
      gType: 0,
      category: "Slot",
    },
    {
      name: "Wealthway",
      img: "https://i.ibb.co/bNxT7RS/Wealthway.png",
      gameId: 14090,
      gType: 0,
      category: "Slot",
    },
    {
      name: "Dragon Soar",
      img: "https://i.ibb.co/mHbjWC4/Dragon-Soar.png",
      gameId: 14089,
      gType: 0,
      category: "Slot",
    },
    {
      name: "Magic Ace",
      img: "https://i.ibb.co/Wtk0zKs/MagicAce.png",
      gameId: 14088,
      gType: 0,
      category: "Slot",
    },
    {
      name: "Pop Pop Candy",
      img: "https://i.ibb.co/Z6mn2m1/Pop.png",
      gameId: 14087,
      gType: 0,
      category: "Slot",
    },
    {
      name: "Open Sesame Mega",
      img: "https://i.ibb.co/xjcgsyH/Open-Sesame-Mega.png",
      gameId: 14086,
      gType: 0,
      category: "Slot",
    },
    {
      name: "Fruity Bonanza",
      img: "https://i.ibb.co/7vsZXbp/Fruity.png",
      gameId: 14085,
      gType: 0,
      category: "Slot",
    },
    {
      name: "Caishen Coming",
      img: "https://i.ibb.co/ScXbd0k/Caishen.png",
      gameId: 14084,
      gType: 0,
      category: "Slot",
    },
    {
      name: "Coocoo Farm",
      img: "https://i.ibb.co/wsrNVXT/Coocoo.png",
      gameId: 14083,
      gType: 0,
      category: "Slot",
    },
    {
      name: "Elemental Link Water",
      img: "https://i.ibb.co/JvzNqcY/Elemental-Link-Water.png",
      gameId: 14082,
      gType: 0,
      category: "Slot",
    },
    {
      name: "Birds Party Deluxe",
      img: "https://i.ibb.co/ZN9NGgR/Birds-Party-Deluxe.png",
      gameId: 14081,
      gType: 0,
      category: "Slot",
    },
    {
      name: "Elemental Link Fire",
      img: "https://i.ibb.co/JQNhQQR/Elemental-Link-Fire.png",
      gameId: 14080,
      gType: 0,
      category: "Slot",
    },
    {
      name: "Moneybags Man 2",
      img: "https://i.ibb.co/khJhv4n/Moneybags.png",
      gameId: 14079,
      gType: 0,
      category: "Slot",
    },
    {
      name: "Trump Card",
      img: "https://i.ibb.co/DY0rNz6/Trump-Card.png",
      gameId: 14077,
      gType: 0,
      category: "Slot",
    },
    {
      name: "Fortune Neko",
      img: "https://i.ibb.co/y63NYZ6/Fortune-Neko.png",
      gameId: 14075,
      gType: 0,
      category: "Slot",
    },
    {
      name: "Book Of Mystery",
      img: "https://i.ibb.co/K7WNRzF/Book-Of-Mystery.png",
      gameId: 14070,
      gType: 0,
      category: "Slot",
    },
    {
      name: "Prosperity Tiger",
      img: "https://i.ibb.co/sV6gS4d/Prosperity-Tiger.png",
      gameId: 14068,
      gType: 0,
      category: "Slot",
    },
    {
      name: "Glamorous Girl",
      img: "https://i.ibb.co/Q6t8J2L/Glamorous-Girl.png",
      gameId: 14067,
      gType: 0,
      category: "Slot",
    },
    {
      name: "Blossom Of Wealth",
      img: "https://i.ibb.co/Khds7Lq/Blossom-Of-Wealth.png",
      gameId: 14065,
      gType: 0,
      category: "Slot",
    },
    {
      name: "QUEEN OF INCA",
      img: "https://i.ibb.co/hZcsdV2/QUEEN-OF-INCA.png",
      gameId: 32061,
      gType: 32,
      category: "Slot",
    },
    {
      name: "FORTUNE MONEY BOOM",
      img: "https://i.ibb.co/8xZDbcy/FORTUNE-MONEY-BOOM.png",
      gameId: 32060,
      gType: 32,
      category: "Slot",
    },
    {
      name: "LUCKY FORTUNES 3x3",
      img: "https://i.ibb.co/xmTxw31/LUCKY-FORTUNES-3x3.png",
      gameId: 32059,
      gType: 32,
      category: "Slot",
    },
    {
      name: "Fortune Sheep",
      img: "https://i.ibb.co/wSsFjp0/Fortune-Sheep.png",
      gameId: 32058,
      gType: 32,
      category: "Slot",
    },
    {
      name: "Chilihuahua",
      img: "https://i.ibb.co/SyD4MhW/Chilihuahua.png",
      gameId: 32057,
      gType: 32,
      category: "Slot",
    },
    {
      name: "Egypt Bonanza",
      img: "https://i.ibb.co/pW4Dt0d/Egypt-Bonanza.png",
      gameId: 32056,
      gType: 32,
      category: "Slot",
    },
    {
      name: "Super Elements",
      img: "https://i.ibb.co/ynmLFk7/Super-Elements.png",
      gameId: 32055,
      gType: 32,
      category: "Slot",
    },
    {
      name: "Night Market 2",
      img: "https://i.ibb.co/vDp32Lz/Night-Market-2.png",
      gameId: 32054,
      gType: 32,
      category: "Slot",
    },
    {
      name: "Fortune Egg",
      img: "https://i.ibb.co/0KSBNBY/Fortune-Egg.png",
      gameId: 32051,
      gType: 32,
      category: "Slot",
    },
    {
      name: "Win Win Neko",
      img: "https://i.ibb.co/FwKZDFX/Win-Win-Neko.png",
      gameId: 32050,
      gType: 32,
      category: "Slot",
    },
    {
      name: "Zeus",
      img: "https://i.ibb.co/v1p4yQF/Zeus.png",
      gameId: 32049,
      gType: 32,
      category: "Slot",
    },
    {
      name: "Golden Genie",
      img: "https://i.ibb.co/cT75vMj/Golden-Genie.jpg",
      gameId: 32047,
      gType: 32,
      category: "Slot",
    },
    {
      name: "Crazy Buffalo",
      img: "https://i.ibb.co/ZHQbrRL/Crazy-Buffalo.png",
      gameId: 32048,
      gType: 32,
      category: "Slot",
    },
    {
      name: "Merge Magic",
      img: "https://i.ibb.co/N6Csr7W/Merge-Magic.png",
      gameId: 32045,
      gType: 32,
      category: "Slot",
    },
    {
      name: "Sugar Bang Bang",
      img: "https://i.ibb.co/qNQT7tG/Sugar-Bang-Bang.png",
      gameId: 32043,
      gType: 32,
      category: "Slot",
    },
  ];
  
  export const FishShooting = [
    {
      name: "Spirit Tide Legend",
      img: "https://i.ibb.co/pdW9fYS/Spirit-Tide-Legend.png",
      gameId: 7009,
      gType: 7,
      category: "Fish Shooting",
    },
    {
      name: "Fighter Fire",
      img: "https://i.ibb.co/VTMNYPp/Fighter-Fire.png",
      gameId: 7008,
      gType: 7,
      category: "Fish Shooting",
    },
    {
      name: "Fishing Disco",
      img: "https://i.ibb.co/cxxngHs/Fishing-Disco.png",
      gameId: 7007,
      gType: 7,
      category: "Fish Shooting",
    },
    {
      name: "Dragon Master",
      img: "https://i.ibb.co/VHLBLwv/Dragon-Master.png",
      gameId: 7006,
      gType: 7,
      category: "Fish Shooting",
    },
    {
      name: "Fishing Yilufa",
      img: "https://i.ibb.co/Bt02n5B/Fishing-Yilufa.png",
      gameId: 7005,
      gType: 7,
      category: "Fish Shooting",
    },
    {
      name: "Shade Dragons Fishing",
      img: "https://i.ibb.co/zrz0kZg/Shade-Dragons-Fishing.png",
      gameId: 7004,
      gType: 7,
      category: "Fish Shooting",
    },
    {
      name: "Cai Shen Fishing",
      img: "https://i.ibb.co/Bf6fYPD/Cai-Shen-Fishing.png",
      gameId: 7003,
      gType: 7,
      category: "Fish Shooting",
    },
    {
      name: "Dragon Fishing II",
      img: "https://i.ibb.co/RN6QgfL/Dragon-Fishing-II.png",
      gameId: 7002,
      gType: 7,
      category: "Fish Shooting",
    },
    {
      name: "Dragon Fishing",
      img: "https://i.ibb.co/6nNzXYs/Dragon-Fishing.png",
      gameId: 7001,
      gType: 7,
      category: "Fish Shooting",
    },
  ];
  
  export const ArcadeGame = [
    {
      name: "Aviator Extra Bet",
      img: "https://i.ibb.co/kx2cDwx/Aviator-Extra-Bet.png",
      gameId: 9023,
      gType: 9,
      category: "Arcade Game",
    },
    {
      name: "Mines2",
      img: "https://i.ibb.co/Xk8tqjr/Mines2.png",
      gameId: 9021,
      gType: 9,
      category: "Arcade Game",
    },
    {
      name: "Mole Crash",
      img: "https://i.ibb.co/Jxxw2p8/Mole-Crash.png",
      gameId: 9020,
      gType: 9,
      category: "Arcade Game",
    },
    {
      name: "Dice",
      img: "https://i.ibb.co/vv4rDD2/Dice.png",
      gameId: 9019,
      gType: 9,
      category: "Arcade Game",
    },
    {
      name: "Plinko",
      img: "https://i.ibb.co/vYwfz23/Plinko.png",
      gameId: 9018,
      gType: 9,
      category: "Arcade Game",
    },
    {
      name: "Hilo",
      img: "https://i.ibb.co/0mMyNbG/Hilo.png",
      gameId: 9017,
      gType: 9,
      category: "Arcade Game",
    },
    {
      name: "Goal",
      img: "https://i.ibb.co/VSsdxYr/Goal.png",
      gameId: 9016,
      gType: 9,
      category: "Arcade Game",
    },
    {
      name: "Firework Burst",
      img: "https://i.ibb.co/9VnkNgT/Firework-Burst.png",
      gameId: 9015,
      gType: 9,
      category: "Arcade Game",
    },
    {
      name: "Mines",
      img: "https://i.ibb.co/tx0rjp6/Mines.png",
      gameId: 9014,
      gType: 9,
      category: "Arcade Game",
    },
    {
      name: "Galaxy Burst",
      img: "https://i.ibb.co/wMs4WDf/Galaxy-Burst.png",
      gameId: 9013,
      gType: 9,
      category: "Arcade Game",
    },
    {
      name: "Jogo Do Bicho",
      img: "https://i.ibb.co/tDGXMm0/Jogo-Do-Bicho.png",
      gameId: 9012,
      gType: 9,
      category: "Arcade Game",
    },
    {
      name: "Caishen Party",
      img: "https://i.ibb.co/z8zhjfy/Caishen-Party.png",
      gameId: 9011,
      gType: 9,
      category: "Arcade Game",
    },
    {
      name: "Lucky Color Game",
      img: "https://i.ibb.co/br8q2ys/Lucky-Color-Game.png",
      gameId: 9010,
      gType: 9,
      category: "Arcade Game",
    },
    {
      name: "King Of Football",
      img: "https://i.ibb.co/31Ht4FL/King-Of-Football.png",
      gameId: 9009,
      gType: 9,
      category: "Arcade Game",
    },
    {
      name: "Crazy King Kong",
      img: "https://i.ibb.co/vd62k5P/Crazy-King-Kong.png",
      gameId: 9008,
      gType: 9,
      category: "Arcade Game",
    },
    {
      name: "Super Super Fruit",
      img: "https://i.ibb.co/2Yds6Wj/Super-Super-Fruit.png",
      gameId: 9007,
      gType: 9,
      category: "Arcade Game",
    },
    {
      name: "Huaguoshan Legends",
      img: "https://i.ibb.co/5WbvRYg/Huaguoshan-Legends.png",
      gameId: 9006,
      gType: 9,
      category: "Arcade Game",
    },
    {
      name: "Beer Tycoon",
      img: "https://i.ibb.co/44dtDs6/Beer-Tycoon.png",
      gameId: 9004,
      gType: 9,
      category: "Arcade Game",
    },
    {
      name: "Birds And Animals",
      img: "https://i.ibb.co/QbJX0JB/Birds-And-Animals.png",
      gameId: 9003,
      gType: 9,
      category: "Arcade Game",
    },
  
    {
      name: "Classic Mario",
      img: "https://i.ibb.co/ckrsqVb/Classic-Mario.png",
      gameId: 9001,
      gType: 9,
      category: "Arcade Game",
    },
  
    {
      name: "Hotline",
      img: "https://i.ibb.co/kxXrZh2/Hotline.png",
      gameId: 22009,
      gType: 22,
      category: "Arcade Game",
    },
    {
      name: "Mini Roulette",
      img: "https://i.ibb.co/JRHVCw8/Mini-Roulette.png",
      gameId: 22008,
      gType: 22,
      category: "Arcade Game",
    },
    {
      name: "Keno",
      img: "https://i.ibb.co/Vm3cBHk/Keno.png",
      gameId: 22007,
      gType: 22,
      category: "Arcade Game",
    },
    {
      name: "Hilo",
      img: "https://i.ibb.co/5FdWJjp/Hilo.png",
      gameId: 22006,
      gType: 22,
      category: "Arcade Game",
    },
    {
      name: "Mines",
      img: "https://i.ibb.co/XFqJGdR/Mines.png",
      gameId: 22005,
      gType: 22,
      category: "Arcade Game",
    },
    {
      name: "Plinko",
      img: "https://i.ibb.co/gTGZfG2/Plinko.png",
      gameId: 22004,
      gType: 22,
      category: "Arcade Game",
    },
    {
      name: "Goal",
      img: "https://i.ibb.co/CndhRgr/Goal.png",
      gameId: 22003,
      gType: 22,
      category: "Arcade Game",
    },
    {
      name: "Dice",
      img: "https://i.ibb.co/Lzh7zsx/Dice.png",
      gameId: 22002,
      gType: 22,
      category: "Arcade Game",
    },
    {
      name: "Aviator",
      img: "https://i.ibb.co/G3cMvSt/Aviator.png",
      gameId: 22001,
      gType: 22,
      category: "Arcade Game",
    },
  ];
  
  export const CardGame = [
    {
      name: "Tongits Rush",
      img: "https://i.ibb.co/RhyjDNd/Tongits-Rush.png",
      gameId: 18029,
      gType: 18,
      category: "CardGame",
    },
    {
      name: "Tongits Fight",
      img: "https://i.ibb.co/G9ymtst/Tongits-Fight.png",
      gameId: 18028,
      gType: 18,
      category: "CardGame",
    },
    {
      name: "Pusoy Rush",
      img: "https://i.ibb.co/DLy8kpW/Pusoy-Rush.png",
      gameId: 18027,
      gType: 18,
      category: "CardGame",
    },
    {
      name: "Dragon Tiger - Joker Bonus",
      img: "https://i.ibb.co/xfd5ZJ7/Dragon-Tiger-Joker-Bonus.png",
      gameId: 18026,
      gType: 18,
      category: "CardGame",
    },
    {
      name: "Tongits",
      img: "https://i.ibb.co/YLS8vZM/Tongits.png",
      gameId: 18025,
      gType: 18,
      category: "CardGame",
    },
    {
      name: "Pusoy",
      img: "https://i.ibb.co/bWLchH7/Pusoy.png",
      gameId: 18024,
      gType: 18,
      category: "CardGame",
    },
    {
      name: "San Gong",
      img: "https://i.ibb.co/w4TqwGv/San-Gong.png",
      gameId: 18023,
      gType: 18,
      category: "CardGame",
    },
    {
      name: "Poker Racing",
      img: "https://i.ibb.co/pZy8zJZ/Poker-Racing.png",
      gameId: 18022,
      gType: 18,
      category: "CardGame",
    },
    {
      name: "Scale",
      img: "https://i.ibb.co/dbH6V9z/Scale.png",
      gameId: 18021,
      gType: 18,
      category: "CardGame",
    },
    {
      name: "Minesweeper",
      img: "https://i.ibb.co/rfStSx0/Minesweeper.jpg",
      gameId: 18020,
      gType: 18,
      category: "CardGame",
    },
    {
      name: "Tongbi Liu Niu",
      img: "https://i.ibb.co/yff7wJY/Tongbi-Liu-Niu.png",
      gameId: 18013,
      gType: 18,
      category: "CardGame",
    },
    {
      name: "Qiang Zhuang Liu Niu",
      img: "https://i.ibb.co/8dY7yxq/Qiang-Zhuang-Liu-Niu.jpg",
      gameId: 18005,
      gType: 18,
      category: "CardGame",
    },
    {
      name: "Ya Zhuang Acey Deucey",
      img: "https://i.ibb.co/cgjRcVp/Ya-Zhuang-Acey-Deucey.png",
      gameId: 18004,
      gType: 18,
      category: "CardGame",
    },
    {
      name: "Qz Nui Nui",
      img: "https://i.ibb.co/MR8qX4b/Qz-Nui-Nui.png",
      gameId: 18002,
      gType: 18,
      category: "CardGame",
    },
    {
      name: "Tongbi Niu Niu",
      img: "https://i.ibb.co/m4Z2TMx/Tongbi-Niu-Niu.png",
      gameId: 18001,
      gType: 18,
      category: "CardGame",
    },
  
    {
      name: "Andar Bahar",
      img: "https://i.ibb.co/PTK8gh0/Andar-Bahar.png",
      gameId: 93031,
      gType: 93,
      category: "Card Game",
    },
    {
      name: "Teen Patti 20-20",
      img: "https://i.ibb.co/JchCpxC/Teen-Patti-20-20.png",
      gameId: 93030,
      gType: 93,
      category: "Card Game",
    },
  ];
  
  export const Bingo = [
    {
      name: "Happy Lottery",
      img: "https://i.ibb.co/tDnPfxX/Happy-Lottery.png",
      gameId: 12003,
      gType: 12,
      category: "Bingo",
    },
    {
      name: "Gold Rooster Lottery",
      img: "https://i.ibb.co/Kw0Rtx3/Gold-Rooster-Lottery.png",
      gameId: 12002,
      gType: 12,
      category: "Bingo",
    },
    {
      name: "Cai Shen Bingo",
      img: "https://i.ibb.co/hyfcMdx/Cai-Shen-Bingo.png",
      gameId: 12001,
      gType: 12,
      category: "Bingo",
    },
  
    {
      name: "EZ Bingo",
      img: "https://i.ibb.co/z6TZDY3/EZ-Bingo.png",
      gameId: 60011,
      gType: 60,
      category: "Bingo",
    },
    {
      name: "Joy Bingo",
      img: "https://i.ibb.co/j4N7QZ4/Joy-Bingo.png",
      gameId: 60010,
      gType: 60,
      category: "Bingo",
    },
    {
      name: "Lightning Bingo",
      img: "https://i.ibb.co/WtP98mj/Lightning-Bingo.png",
      gameId: 60009,
      gType: 60,
      category: "Bingo",
    },
    {
      name: "Heat Bingo",
      img: "https://i.ibb.co/74FY3Q1/Heat-Bingo.png",
      gameId: 60008,
      gType: 60,
      category: "Bingo",
    },
    {
      name: "Money Bingo",
      img: "https://i.ibb.co/74MSbDG/Money-Bingo.png",
      gameId: 60007,
      gType: 60,
      category: "Bingo",
    },
    {
      name: "Beasty Bingo",
      img: "https://i.ibb.co/K2G1dQ2/Beasty-Bingo.png",
      gameId: 60006,
      gType: 60,
      category: "Bingo",
    },
    {
      name: "Bingo Bonanza",
      img: "https://i.ibb.co/sJG76qC/Bingo-Bonanza.png",
      gameId: 60005,
      gType: 60,
      category: "Bingo",
    },
    {
      name: "Atlantis",
      img: "https://i.ibb.co/PgQ8gKY/Atlantis.png",
      gameId: 60004,
      gType: 60,
      category: "Bingo",
    },
    {
      name: "Bingo Bingo",
      img: "https://i.ibb.co/fqkZFb2/Bingo-Bingo.png",
      gameId: 60003,
      gType: 60,
      category: "Bingo",
    },
    {
      name: "Open Sesame",
      img: "https://i.ibb.co/rMJxWzL/Open-Sesame.png",
      gameId: 60002,
      gType: 60,
      category: "Bingo",
    },
  ];
  
  export const LiveGame = [
    {
      name: "HOT 7up 7down",
      img: "https://i.ibb.co/dPM7N66/HOT-7up-7down.png",
      gameId: 41008,
      gType: 41,
      category: "Live Game",
    },
    {
      name: "Hot Baccarat",
      img: "https://i.ibb.co/HXbHCsP/Hot-Baccarat.png",
      gameId: 41007,
      gType: 41,
      category: "Live Game",
    },
    {
      name: "Hot Color Game",
      img: "https://i.ibb.co/k52R5PL/Hot-Color-Game.png",
      gameId: 41006,
      gType: 41,
      category: "Live Game",
    },
    {
      name: "Hot Sicbo",
      img: "https://i.ibb.co/bK3PnhM/Hot-Sicbo.png ",
      gameId: 41005,
      gType: 41,
      category: "Live Game",
    },
    {
      name: "Hot Roulette",
      img: "https://i.ibb.co/qrMyj97/Roulette.png",
      gameId: 41004,
      gType: 41,
      category: "Live Game",
    },
    {
      name: "Dragon Tiger",
      img: "https://i.ibb.co/72WjbMS/Dragon-Tiger.png",
      gameId: 41003,
      gType: 41,
      category: "Live Game",
    },
    {
      name: "Roulette",
      img: "https://i.ibb.co/rZF5XRf/Roulette.png",
      gameId: 41002,
      gType: 41,
      category: "Live Game",
    },
    {
      name: "Baccarat",
      img: "https://i.ibb.co/HTQ0DCL/Baccarat.png",
      gameId: 41001,
      gType: 41,
      category: "Live Game",
    },
  ];
  